Finance/Models/FinancialGoal.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Finance.Models
{
    public class FinancialGoal
    {
        [Key]
        public int Id { get; set; } // Chave primária
        public decimal Amount { get; set; } // Valor da meta financeira
        public string Name { get; set; } // Nome da meta
        public DateTime CreatedOn { get; set; } // Data de criação da meta
        public DateTime? EstimatedCompletion { get; set; } // Previsão de término (opcional)
        public string Status { get; set; } // Status da meta (ex: Active, Completed, Cancelled)
        public int Parcelas { get; set; }
        public int ParcelaAtual { get; set; }
        public bool Check { get; set; }
        public string Description { get; set; }
        public decimal InstallmentValue { get; set; }
        public bool IsPaidThisMonth { get; set; }
        public DateTime? LastPaymentDate { get; set; }
        [ForeignKey("CategoryFinance")]
        public int CategoryId { get; set; }
        public CategoryFinance Category { get; set; }
        public FinancialGoal()
        {
            // Inicialização de valores padrão
            Amount = 0;
            Name = "Nova Meta Financeira";
            CreatedOn = DateTime.Now;
            EstimatedCompletion = null;
            Status = "Active";
        }
    }
}

Finance/Controllers/FinancialGoalsController.cs
using Finance.Data;
using Finance.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Finance.Controllers
{
    public class FinancialGoalsController : Controller
    {
        private readonly FinanceContext _context;

        public FinancialGoalsController(FinanceContext context)
        {
            _context = context;
        }

        // GET: FinancialGoals
        public async Task<IActionResult> Index()
        {
            var financialGoals = _context.FinancialGoal.Include(f => f.Category).ToListAsync();
            return View(await financialGoals);
        }

        // GET: FinancialGoals/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var financialGoal = await _context.FinancialGoal
                .Include(f => f.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (financialGoal == null)
            {
                return NotFound();
            }

            return View(financialGoal);
        }

        // GET: FinancialGoals/Create
        public IActionResult Create()
        {
            ViewBag.Categories = _context.CategoryFinances.ToList();
            return View();
        }

        // POST: FinancialGoals/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Amount,Name,CreatedOn,EstimatedCompletion,Parcelas,Description,ParcelaAtual,Check,Status,InstallmentValue,CategoryId")] FinancialGoal financialGoal)
        {
            if (ModelState.IsValid)
            {
                _context.Add(financialGoal);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Categories = _context.CategoryFinances.ToList();
            return View(financialGoal);
        }

        // GET: FinancialGoals/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var financialGoal = await _context.FinancialGoal.FindAsync(id);
            if (financialGoal == null)
            {
                return NotFound();
            }
            ViewBag.Categories = _context.CategoryFinances.ToList();
            return View(financialGoal);
        }

        // POST: FinancialGoals/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Amount,Name,CreatedOn,EstimatedCompletion,Description,Parcelas,ParcelaAtual,Check,Status,InstallmentValue,CategoryId")] FinancialGoal financialGoal)
        {
            if (id != financialGoal.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(financialGoal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FinancialGoalExists(financialGoal.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Categories = _context.CategoryFinances.ToList();
            return View(financialGoal);
        }

        // GET: FinancialGoals/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var financialGoal = await _context.FinancialGoal
                .Include(f => f.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (financialGoal == null)
            {
                return NotFound();
            }

            return View(financialGoal);
        }

        // POST: FinancialGoals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var financialGoal = await _context.FinancialGoal.FindAsync(id);
            if (financialGoal != null)
            {
                _context.FinancialGoal.Remove(financialGoal);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FinancialGoalExists(int id)
        {
            return _context.FinancialGoal.Any(e => e.Id == id);
        }
    }
}

Finance/Views/FinancialGoals/Create.cshtml
@model Finance.Models.FinancialGoal

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>FinancialGoal</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedOn" class="control-label"></label>
                <input asp-for="CreatedOn" class="form-control" />
                <span asp-validation-for="CreatedOn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstimatedCompletion" class="control-label"></label>
                <input asp-for="EstimatedCompletion" class="form-control" />
                <span asp-validation-for="EstimatedCompletion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Parcelas" class="control-label"></label>
                <input asp-for="Parcelas" class="form-control" />
                <span asp-validation-for="Parcelas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ParcelaAtual" class="control-label"></label>
                <input asp-for="ParcelaAtual" class="form-control" />
                <span asp-validation-for="ParcelaAtual" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InstallmentValue" class="control-label"></label>
                <input asp-for="InstallmentValue" class="form-control" />
                <span asp-validation-for="InstallmentValue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Finance/Views/FinancialGoals/Delete.cshtml
@model Finance.Models.FinancialGoal

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>FinancialGoal</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstimatedCompletion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstimatedCompletion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Finance/Views/FinancialGoals/Details.cshtml
@model Finance.Models.FinancialGoal

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>FinancialGoal</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstimatedCompletion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstimatedCompletion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Parcelas)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ParcelaAtual)
        </dt>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Check)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Finance/Views/FinancialGoals/Edit.cshtml
@model Finance.Models.FinancialGoal

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>FinancialGoal</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedOn" class="control-label"></label>
                <input asp-for="CreatedOn" class="form-control" />
                <span asp-validation-for="CreatedOn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstimatedCompletion" class="control-label"></label>
                <input asp-for="EstimatedCompletion" class="form-control" />
                <span asp-validation-for="EstimatedCompletion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Parcelas" class="control-label"></label>
                <input asp-for="Parcelas" class="form-control" />
                <span asp-validation-for="Parcelas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ParcelaAtual" class="control-label"></label>
                <input asp-for="ParcelaAtual" class="form-control" />
                <span asp-validation-for="ParcelaAtual" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InstallmentValue" class="control-label"></label>
                <input asp-for="InstallmentValue" class="form-control"  />
                <span asp-validation-for="InstallmentValue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Check" class="control-label"></label>
                <input asp-for="Check" class="form-control" />
                <span asp-validation-for="Check" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script>
    document.querySelectorAll('input[type="number"]').forEach(function (input) {
        input.addEventListener('input', function (event) {
            this.value = this.value.replace(',', '.');
        });
    });
</script>

Finance/Views/FinancialGoals/Index.cshtml
@model IEnumerable<Finance.Models.FinancialGoal>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Amount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedOn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EstimatedCompletion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Parcelas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ParcelaAtual)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InstallmentValue)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Check)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Amount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedOn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EstimatedCompletion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Parcelas)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ParcelaAtual)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.InstallmentValue)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Check)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>


<div class="w-75">
    <div class="card">
        <div class="card-header d-flex justify-content-between">
            <div class="d-flex gap-2">
                <h5 class="card-title">Contas pagando</h5>
                <span class="material-symbols-outlined">
                    paid
                </span>
            </div>
            <a class="nav-link" href="@Url.Action("Create", "FinancialGoals")">
                <span class="material-symbols-outlined">
                    add
                </span>
            </a>
        </div>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th style="width:20%;">Name</th>
                    <th style="width:25%">Termino Previsto</th>
                    <th class="d-none d-md-table-cell" style="width:25%">Parcelas</th>
                    <th>Description</th>
                    <th>Pago</th>
                    <th>Ação</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var goal in Model)
                {
                    if (goal.Status == "Pagando")
                    {
                        <tr>
                            <td>@goal.Name</td>
                            <td>@goal.EstimatedCompletion?.ToString("dd/MM")</td>
                            <td class="d-none d-md-table-cell">@goal.ParcelaAtual/@goal.Parcelas</td>
                            <td>@goal.Description</td>
                            <td>
                                @{
                                    if (goal.IsPaidThisMonth)
                                    {
                                        <span class="material-symbols-outlined">
                                            check
                                        </span>
                                    }
                                    else
                                    {
                                        @:Não
                                    }
                                }
                            </td>
                            <td>
                                @if (!goal.IsPaidThisMonth)
                                {
                                    <form asp-action="PayInstallment" method="post">
                                        <input type="hidden" name="id" value="@goal.Id" />
                                        <button type="submit" class="btn btn-success">
                                            Pagar
                                            <span class="material-symbols-outlined">
                                                savings
                                            </span>
                                        </button>
                                    </form>
                                }
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>

<div class="w-25">
    <div class="card">
        <div class="card-header d-flex justify-content-between">
            <div class="d-flex gap-2">
                <h5 class="card-title">Contas a pagar</h5>
                <span class="material-symbols-outlined">
                    money_off
                </span>
            </div>
            <a class="nav-link" href="@Url.Action("Create", "FinancialGoals")">
                <span class="material-symbols-outlined">
                    add
                </span>
            </a>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Status</th>
                    <th>Valor</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var goal in Model)
                {
                    if (goal.Status != "Pagando")
                    {
                        <tr>
                            <td>@goal.Name</td>
                            <td>@goal.Status</td>
                            <td>@goal.Amount</td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>